server:
  port: 8080
eureka:
  instance:
    hostname: crond.jgz.com
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    ip-address: 47.75.134.108
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://jgz:modubiz@47.75.134.108:8761/eureka/
spring:
  application:
    name: exchange-crond
  profiles:
    active: staging
  datasource:
    url: jdbc:mysql://localhost:3306/exchange_crond
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-active: 200
      max-wait: 10000
      test-on-borrow: true
  jpa:
    hibernate:
      ddl-auto: update #important! Don't change!
      use-new-id-generator-mappings: true
    show-sql: false
  resources:
    chain:
      enabled: true
  data:
    rest:
      base-path: /
  redis:
    host: localhost
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 200
        max-wait: -1ms
        max-idle: 50
        min-idle: 0
#    cluster:
#      nodes:
#        - 47.74.245.55:6390
#        - 47.74.245.55:6391
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZZ
    default-property-inclusion: non_null
---
spring:
  profiles: scratch
  datasource:
    url: jdbc:mysql://rm-t4nreoh5f58l5o2176o.mysql.singapore.rds.aliyuncs.com:3306/exchange_crond_scratch?useSSL=false
    username: root
    password: '*o#22#rxYibv'
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
logging:
  level:
    com:
      jgz:
        exchange:
         proxies: DEBUG
---
spring:
  profiles: development
  datasource:
    url: jdbc:mysql://rm-t4nreoh5f58l5o2176o.mysql.singapore.rds.aliyuncs.com:3306/exchange_crond_development?useSSL=false
    username: root
    password: '*o#22#rxYibv'
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create #Dangerous!
logging:
  level:
    com:
      jgz:
        exchange:
         proxies: INFO
server:
  port: 8070
---
spring:
  profiles: staging
  datasource:
    url: jdbc:mysql://rm-t4nreoh5f58l5o217.mysql.singapore.rds.aliyuncs.com:3306/exchange_crond_staging?useSSL=false
    username: root
    password: '*o#22#rxYibv'
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: r-t4nfb37c4e638304.redis.singapore.rds.aliyuncs.com
    port: 6379
    password: n5CdC82AKXCwkLM8
logging:
  level:
    com:
      jgz:
        exchange:
         proxies: INFO
---
spring:
  profiles: production
  datasource:
    url:
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
---
spring:
  profiles: https
server:
  port: 443
  ssl:
    key-store: ''
    key-store-password: ''
    key-password: ''